# Include bitherder userspace
USER_NAME := bitherder

RGBLIGHT_ENABLE = yes
BACKLIGHT_ENABLE = no
MOUSEKEY_ENABLE = no
COMBO_ENABLE = yes
LEADER_ENABLE = yes
AUDIO_ENABLE = yes

# Memory reductions
LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
ENCODER_ENABLE = no
